WorkingWithLocalStorageApp/Models/EnvironmentType.cs
namespace WorkingWithLocalStorageApp.Models;
public enum EnvironmentType
{
    Development,
    Production
}

WorkingWithLocalStorageApp/Models/Person.cs
namespace WorkingWithLocalStorageApp.Models;

public class Person
{
    public int Id { get; set; }
    public string  FirstName { get; set; }
    public string LastName { get; set; }
    public override string ToString() => $"{Id,-4}{FirstName} {LastName}";
}

WorkingWithLocalStorageApp/Models/SecretVault.cs
using WorkingWithLocalStorageApp.Interfaces;

namespace WorkingWithLocalStorageApp.Models;

public class SecretVault : ISecretVault
{
    public string Key { get; set; }
    public string Password { get; set; }
    public string Salt { get; set; }
}

WorkingWithLocalStorageApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace WorkingWithLocalStorageApp.Pages;
[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

WorkingWithLocalStorageApp/Pages/Index.cshtml.cs
using Hanssens.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkingWithLocalStorageApp.Classes;
using WorkingWithLocalStorageApp.Models;


namespace WorkingWithLocalStorageApp.Pages;
public class IndexModel : PageModel
{
    string LocalStorageKey => LocalSetup.Instance.Key;
    private LocalStorage _localStorage;

    [BindProperty]
    public Person Person { get; set; }

    public IndexModel(ILocalStorage storage) 
        => _localStorage = storage as LocalStorage;

    public void OnGet() { }

    public RedirectToPageResult OnPostSetLocalToLocalStorage()
    {
        Person.Id = 1;
        _localStorage.Store(LocalStorageKey,Person);
        _localStorage.Persist();
        
        return RedirectToPage("ViewPage");
    }

    public void OnPostGetFromLocalStorage()
    {
        var person = _localStorage.Get<Person>(LocalStorageKey);

        Log.Information("Person: {person}", person);
    }
}

WorkingWithLocalStorageApp/Pages/ViewPage.cshtml.cs
using Hanssens.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WorkingWithLocalStorageApp.Classes;
using WorkingWithLocalStorageApp.Models;

namespace WorkingWithLocalStorageApp.Pages;

public class ViewPageModel : PageModel
{
    private LocalStorage _localStorage;

    [BindProperty]
    public Person Person { get; set; }

    public ViewPageModel(ILocalStorage storage) 
        => _localStorage = storage as LocalStorage;

    public void OnGet()
    {
        Person = _localStorage.Get<Person>(LocalSetup.Instance.Key);
    }
}

WorkingWithLocalStorageApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container">
    <h1 class="fs-5">Welcome</h1>
    <form id="main" method="post">

        <div class="mb-3">
            <label for="firstName" class="form-label">First name</label>
            <input type="text" asp-for="Person.FirstName" class="form-control kpwidth" id="firstName">
        </div>

        <div class="mb-3">
            <label for="lastName" class="form-label">Last name</label>
            <input type="text" asp-for="Person.LastName" class="form-control kpwidth" id="lastName">
        </div>

        <div class="row">
            <div class="col-auto pt-2 ps-3 pb-2 ">

                <input type="submit"
                       asp-page-handler="SetLocalToLocalStorage"
                       value="Set" class="btn btn-primary "/>

            </div>

            <div class="col-auto pt-2 ps-5 pb-2 ">

                <input type="submit"
                       asp-page-handler="GetFromLocalStorage"
                       value="Get" class="btn btn-primary "/>

            </div>
        </div>
    </form>
</div>

WorkingWithLocalStorageApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - workingwithlocalstorageapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WorkingWithLocalStorageApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                Code sample
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Code sample
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WorkingWithLocalStorageApp/Pages/ViewPage.cshtml
@page
@model WorkingWithLocalStorageApp.Pages.ViewPageModel
@{
}

<h1 class="fs-5">From index</h1>

<div class="row">
    <div class="col-1 fw-bold text-end">
        First
    </div>
    <div class="col">
        @Model.Person.FirstName
    </div>
</div>

<div class="row">
    <div class="col-1 fw-bold  text-end">
        Last
    </div>
    <div class="col">
        @Model.Person.LastName
    </div>
</div>